<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB; 

class GeneralSettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('general_settings')->insert([
        [
         'setting_type' =>  '1',
         'setting_name' => 'favicon',
         'filed_label' => 'Favicon (25*25)',
         'filed_name' => 'favicon',
         'filed_type' => 'file',
         'filed_value' => '',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '1',
         'setting_name' => 'logo',
         'filed_label' => 'Logo',
         'filed_name' => 'logo',
         'filed_type' => 'file',
         'filed_value' => '',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '1',
         'setting_name' => 'application_name',
         'filed_label' => 'Application Name',
         'filed_name' => 'application_name',
         'filed_type' => 'text',
         'filed_value' => 'Adiyogi Technosoft',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '1',
         'setting_name' => 'timezone',
         'filed_label' => 'Time Zone',
         'filed_name' => 'timezone',
         'filed_type' => 'text',
         'filed_value' => 'Asia/Kolkata',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '1',
         'setting_name' => 'currency',
         'filed_label' => 'Currency',
         'filed_name' => 'currency',
         'filed_type' => 'text',
         'filed_value' => 'INR',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '1',
         'setting_name' => 'copyright',
         'filed_label' => 'Copyright',
         'filed_name' => 'copyright',
         'filed_type' => 'text',
         'filed_value' => 'Copyright © 2021 Adiyogi Technosoft Pvt. Ltd.  All rights reserved.',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '1',
         'setting_name' => 'meta_title',
         'filed_label' => 'Site Meta Title',
         'filed_name' => 'meta_title',
         'filed_type' => 'text',
         'filed_value' => 'Adiyogi Technosoft - IT Company in Jodhpur | Web and App Development',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '1',
         'setting_name' => 'meta_keyword',
         'filed_label' => 'Site Meta Keyword',
         'filed_name' => 'meta_keyword',
         'filed_type' => 'text',
         'filed_value' => 'Web development company in Jodhpur',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '1',
         'setting_name' => 'meta_description',
         'filed_label' => 'Site Meta Description',
         'filed_name' => 'meta_description',
         'filed_type' => 'textarea',
         'filed_value' => 'Adiyogi Technosoft is the top E-commerce website and mobile app company in Jodhpur. Services include Web & app development, Digital marketing, and SEO.',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '1',
         'setting_name' => 'address',
         'filed_label' => 'Address',
         'filed_name' => 'address',
         'filed_type' => 'text',
         'filed_value' => 'Plot No 276, Opp. Rajasthan Patrika Office, Manji Ka Hatha, Paota, Jodhpur, Rajasthan - 342001',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '1',
         'setting_name' => 'email',
         'filed_label' => 'Email',
         'filed_name' => 'email',
         'filed_type' => 'text',
         'filed_value' => 'info1@adiyogitechnosoft.com',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '1',
         'setting_name' => 'phone',
         'filed_label' => 'Phone',
         'filed_name' => 'phone',
         'filed_type' => 'text',
         'filed_value' => '+91-9785869100',
         'field_options' => '',
         'is_require' => '1',
        ],        
        [
         'setting_type' =>  '1',
         'setting_name' => 'firebasekey',
         'filed_label' => 'Firebase Key',
         'filed_name' => 'firebasekey',
         'filed_type' => 'textarea',
         'filed_value' => '',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '2',
         'setting_name' => 'email_from',
         'filed_label' => 'Email From/ Reply to',
         'filed_name' => 'email_from',
         'filed_type' => 'text',
         'filed_value' => 'info@adiyogitechnosoft.com',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '2',
         'setting_name' => 'smtp_host',
         'filed_label' => 'SMTP Host',
         'filed_name' => 'smtp_host',
         'filed_type' => 'text',
         'filed_value' => 'adiyogitechnosoft.com',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '2',
         'setting_name' => 'smtp_port',
         'filed_label' => 'SMTP Port',
         'filed_name' => 'smtp_port',
         'filed_type' => 'text',
         'filed_value' => '465',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '2',
         'setting_name' => 'smtp_user',
         'filed_label' => 'SMTP User',
         'filed_name' => 'smtp_user',
         'filed_type' => 'text',
         'filed_value' => 'info@adiyogitechnosoft.com',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '2',
         'setting_name' => 'smtp_pass',
         'filed_label' => 'SMTP Password',
         'filed_name' => 'smtp_pass',
         'filed_type' => 'password',
         'filed_value' => 'ayt@123#176',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '3',
         'setting_name' => 'facebook_link',
         'filed_label' => 'Facebook',
         'filed_name' => 'facebook_link',
         'filed_type' => 'text',
         'filed_value' => 'https://www.facebook.com/adiyogijodhpur',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '3',
         'setting_name' => 'twitter_link',
         'filed_label' => 'Twitter',
         'filed_name' => 'twitter_link',
         'filed_type' => 'text',
         'filed_value' => 'https://twitter.com/AdiyogiRajesh',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '3',
         'setting_name' => 'youtube_link',
         'filed_label' => 'Youtube',
         'filed_name' => 'youtube_link',
         'filed_type' => 'text',
         'filed_value' => 'https://www.youtube.com/channel/UCbmF3NzKoDs2y8xc2oS-98Q',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '3',
         'setting_name' => 'linkedin_link',
         'filed_label' => 'LinkedIn',
         'filed_name' => 'linkedin_link',
         'filed_type' => 'text',
         'filed_value' => 'https://www.linkedin.com/company/adiyogitechnosoft',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '3',
         'setting_name' => 'instagram_link',
         'filed_label' => 'Instagram',
         'filed_name' => 'instagram_link',
         'filed_type' => 'text',
         'filed_value' => 'https://www.instagram.com/adiyogitechnosoft/',
         'field_options' => '',
         'is_require' => '1',
        ], 
        [
         'setting_type' =>  '4',
         'setting_name' => 'sms_url',
         'filed_label' => 'SMS URL',
         'filed_name' => 'sms_url',
         'filed_type' => 'text',
         'filed_value' => 'http://sms',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '4',
         'setting_name' => 'sms_sender',
         'filed_label' => 'SMS Sender ID',
         'filed_name' => 'sms_sender',
         'filed_type' => 'text',
         'filed_value' => 'demo',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '4',
         'setting_name' => 'sms_password',
         'filed_label' => 'SMS Password',
         'filed_name' => 'sms_password',
         'filed_type' => 'text',
         'filed_value' => 'demo',
         'field_options' => '',
         'is_require' => '1',
        ], 
        [
         'setting_type' =>  '5',
         'setting_name' => 'google_iframe',
         'filed_label' => 'Google Iframe',
         'filed_name' => 'google_iframe',
         'filed_type' => 'textarea',
         'filed_value' => '',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '5',
         'setting_name' => 'tawk_chat',
         'filed_label' => 'Tawk Chat',
         'filed_name' => 'tawk_chat',
         'filed_type' => 'textarea',
         'filed_value' => '',
         'field_options' => '',
         'is_require' => '1',
        ], 
        [
         'setting_type' =>  '5',
         'setting_name' => 'whatsapp_button',
         'filed_label' => 'WhatsApp Button',
         'filed_name' => 'whatsapp_button',
         'filed_type' => 'textarea',
         'filed_value' => '',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '5',
         'setting_name' => 'google_analytics',
         'filed_label' => 'Google Analytics',
         'filed_name' => 'google_analytics',
         'filed_type' => 'textarea',
         'filed_value' => '',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '6',
         'setting_name' => 'is_payment',
         'filed_label' => 'Payment',
         'filed_name' => 'is_payment',
         'filed_type' => 'select',
         'filed_value' => '0',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '6',
         'setting_name' => 'razorpay_keyid',
         'filed_label' => 'Razor Key Id',
         'filed_name' => 'razorpay_keyid',
         'filed_type' => 'text',
         'filed_value' => 'rzp_test_hjtIGVzzfwOIZ5',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '6',
         'setting_name' => 'razorpay_secretkey',
         'filed_label' => 'Razor Key Secret',
         'filed_name' => 'razorpay_secretkey',
         'filed_type' => 'text',
         'filed_value' => 'PAOzbh6QlOr7mIeeojTiC4qE',
         'field_options' => '',
         'is_require' => '1',
        ], 
        [
         'setting_type' =>  '6',
         'setting_name' => 'gst_number',
         'filed_label' => 'Company GST Number',
         'filed_name' => 'gst_number',
         'filed_type' => 'text',
         'filed_value' => 'SDFSD216546',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '6',
         'setting_name' => 'pan_number',
         'filed_label' => 'PAN Number',
         'filed_name' => 'pan_number',
         'filed_type' => 'text',
         'filed_value' => 'DSTS15687',
         'field_options' => '',
         'is_require' => '1',
        ],
        [
         'setting_type' =>  '6',
         'setting_name' => 'merchant_id',
         'filed_label' => 'Razor Merchant Id',
         'filed_name' => 'merchant_id',
         'filed_type' => 'text',
         'filed_value' => 'HvjKAdDuo013Kq',
         'field_options' => '',
         'is_require' => '1',
        ],
        ]);
    }
}
